services:
  postgres_db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      - POSTGRES_USER=heather
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=swim
    ports:
      - 5432:5432

